from __future__ import annotations
import collections.abc
import datetime
import typing
__all__: list[str] = ['AllianceLog', 'UserLog']
class AllianceLog:
    class Member:
        def __init__(self, id: typing.SupportsInt, username: str, joined: datetime.datetime, flights: typing.SupportsInt, contributed: typing.SupportsInt, daily_contribution: typing.SupportsInt, online: datetime.datetime, sv: typing.SupportsFloat, season: typing.SupportsInt) -> None:
            ...
        @property
        def contributed(self) -> int:
            ...
        @property
        def daily_contribution(self) -> int:
            ...
        @property
        def flights(self) -> int:
            ...
        @property
        def id(self) -> int:
            ...
        @property
        def joined(self) -> datetime.datetime:
            ...
        @property
        def online(self) -> datetime.datetime:
            ...
        @property
        def season(self) -> int:
            ...
        @property
        def sv(self) -> float:
            ...
        @property
        def username(self) -> str:
            ...
    def __init__(self, id: typing.SupportsInt, name: str, rank: typing.SupportsInt, member_count: typing.SupportsInt, max_members: typing.SupportsInt, value: typing.SupportsFloat, ipo: bool, min_sv: typing.SupportsFloat, members: collections.abc.Sequence[AllianceLog.Member]) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @property
    def ipo(self) -> bool:
        ...
    @property
    def log_id(self) -> str:
        ...
    @property
    def log_time(self) -> datetime.datetime:
        ...
    @property
    def max_members(self) -> int:
        ...
    @property
    def member_count(self) -> int:
        ...
    @property
    def members(self) -> list[AllianceLog.Member]:
        ...
    @property
    def min_sv(self) -> float:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def rank(self) -> int:
        ...
    @property
    def value(self) -> float:
        ...
class UserLog:
    class AircraftCount:
        @property
        def aircraft(self) -> str:
            ...
        @property
        def amount(self) -> int:
            ...
    class Award:
        def __init__(self, ts: datetime.datetime, award: str) -> None:
            ...
        @property
        def award(self) -> str:
            ...
        @property
        def ts(self) -> datetime.datetime:
            ...
    class RouteDetail:
        @property
        def arrived(self) -> datetime.datetime:
            ...
        @property
        def destination(self) -> str:
            ...
        @property
        def distance(self) -> int:
            ...
        @property
        def origin(self) -> str:
            ...
        @property
        def stopover(self) -> str:
            ...
    class Share:
        def __init__(self, ts: datetime.datetime, share: typing.SupportsFloat) -> None:
            ...
        @property
        def share(self) -> float:
            ...
        @property
        def ts(self) -> datetime.datetime:
            ...
    def __init__(self, id: typing.SupportsInt, username: str, level: typing.SupportsInt, online: bool, share: typing.SupportsFloat, shares_available: typing.SupportsInt, shares_sold: typing.SupportsInt, ipo: bool, fleet_count: typing.SupportsInt, routes: typing.SupportsInt, alliance: str, achievements: typing.SupportsInt, game_mode: bool, rank: typing.SupportsInt, reputation: typing.SupportsInt, cargo_reputation: typing.SupportsInt, founded: datetime.datetime, logo: str, share_log: collections.abc.Sequence[UserLog.Share], awards: collections.abc.Sequence[UserLog.Award], fleet: collections.abc.Sequence[UserLog.AircraftCount], route_list: collections.abc.Sequence[UserLog.RouteDetail]) -> None:
        ...
    @property
    def achievements(self) -> int:
        ...
    @property
    def alliance(self) -> str:
        ...
    @property
    def awards(self) -> list[UserLog.Award]:
        ...
    @property
    def cargo_reputation(self) -> int:
        ...
    @property
    def fleet(self) -> list[UserLog.AircraftCount]:
        ...
    @property
    def fleet_count(self) -> int:
        ...
    @property
    def founded(self) -> datetime.datetime:
        ...
    @property
    def game_mode(self) -> bool:
        ...
    @property
    def ipo(self) -> bool:
        ...
    @property
    def level(self) -> int:
        ...
    @property
    def log_id(self) -> str:
        ...
    @property
    def log_time(self) -> datetime.datetime:
        ...
    @property
    def logo(self) -> str:
        ...
    @property
    def online(self) -> bool:
        ...
    @property
    def rank(self) -> int:
        ...
    @property
    def reputation(self) -> int:
        ...
    @property
    def route_list(self) -> list[UserLog.RouteDetail]:
        ...
    @property
    def routes(self) -> int:
        ...
    @property
    def share(self) -> float:
        ...
    @property
    def share_log(self) -> list[UserLog.Share]:
        ...
    @property
    def shares_available(self) -> int:
        ...
    @property
    def shares_sold(self) -> int:
        ...
    @property
    def username(self) -> str:
        ...
