from __future__ import annotations
__all__: list[str] = ['jaro_distance', 'jaro_winkler_distance']
def jaro_distance(a: str, b: str) -> float:
    ...
def jaro_winkler_distance(a: str, b: str) -> float:
    ...
