import hashlib
import os
from pathlib import Path
from typing import Generator

ROOT = Path(__file__).parent.parent.parent
ASSETS_DIR = ROOT / "am4" / "assets"
WEB_DIR = ROOT / "am4-web"
SW_PATH = WEB_DIR / "sw.js"


def get_asset_list() -> Generator[str, None, None]:
    for r, _, fs in os.walk(ASSETS_DIR):
        for f in fs:
            rel = Path(r).relative_to(ASSETS_DIR)
            web_path = f"/assets/{rel}/{f}" if rel != Path(".") else f"/assets/{f}"
            yield web_path.replace("\\", "/")


def main() -> None:
    assets = sorted(get_asset_list())
    v_str = f"{len(assets)}-{hashlib.md5((assets[0] + assets[-1]).encode()).hexdigest()[:8]}"

    js_content = f"""/* generated by misc/scripts/gen_pwa.py */
const CACHE_NAME = 'am4-cache-v{v_str}';
const ASSETS = {assets!r};

self.addEventListener('install', event => {{
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {{
            console.log('[SW] pre-caching', ASSETS.length, 'files');
            return Promise.allSettled(
                ASSETS.map(url => cache.add(url).catch(e => console.warn('[SW] failed to cache', url, e)))
            );
        }})
    );
}});

self.addEventListener('activate', event => {{
    event.waitUntil(
        caches.keys().then(keys => Promise.all(
            keys.map(key => key !== CACHE_NAME ? caches.delete(key) : Promise.resolve())
        ))
    );
}});

self.addEventListener('fetch', event => {{
    if (event.request.method !== 'GET') return;
    
    event.respondWith(
        caches.match(event.request).then(cached => {{
            return cached || fetch(event.request).then(response => {{
                if (response.status === 200 && response.type === 'basic') {{
                    const clone = response.clone();
                    caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
                }}
                return response;
            }});
        }})
    );
}});
"""
    with open(SW_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)


if __name__ == "__main__":
    main()
