import hashlib
import os
from pathlib import Path
from typing import Generator

ROOT = Path(__file__).parent.parent
ASSETS_DIR = ROOT / "am4" / "assets"
WEB_DIR = ROOT / "am4-web"
SW_PATH = WEB_DIR / "sw.js"


def get_asset_info() -> Generator[tuple[str, str], None, None]:
    for r, _, fs in os.walk(ASSETS_DIR):
        for f in fs:
            full_path = Path(r) / f
            rel = Path(r).relative_to(ASSETS_DIR)
            web_path = f"/assets/{rel}/{f}" if rel != Path(".") else f"/assets/{f}"

            sha256 = hashlib.sha256()
            with open(full_path, "rb") as f_obj:
                while chunk := f_obj.read(8192):
                    sha256.update(chunk)

            yield web_path.replace("\\", "/"), sha256.hexdigest()


def main() -> None:
    assets_info = sorted(list(get_asset_info()), key=lambda x: x[0])
    assets = [x[0] for x in assets_info]

    master_sha = hashlib.sha256()
    for _, file_hash in assets_info:
        master_sha.update(file_hash.encode())

    js_content = f"""/* generated by scripts/{__name__}.py */
const CACHE_NAME = 'am4-cache-{master_sha.hexdigest()}';
const ASSETS = {assets!r};

self.addEventListener('install', event => {{
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {{
            console.log('[SW] pre-caching', ASSETS.length, 'files');
            return Promise.allSettled(
                ASSETS.map(url => cache.add(url).catch(e => console.warn('[SW] failed to cache', url, e)))
            );
        }})
    );
}});

self.addEventListener('activate', event => {{
    event.waitUntil(
        caches.keys().then(keys => Promise.all(
            keys.map(key => key !== CACHE_NAME ? caches.delete(key) : Promise.resolve())
        ))
    );
}});

self.addEventListener('fetch', event => {{
    if (event.request.method !== 'GET') return;
    
    event.respondWith(
        caches.match(event.request).then(cached => {{
            return cached || fetch(event.request).then(response => {{
                if (response.status === 200 && response.type === 'basic') {{
                    const clone = response.clone();
                    caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
                }}
                return response;
            }});
        }})
    );
}});
"""
    with open(SW_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)


if __name__ == "__main__":
    main()
