import hashlib
import json
import os
from pathlib import Path
from typing import Iterable, Sequence

STAGING_DIR = Path(os.environ["TRUNK_STAGING_DIR"])
PUBLIC_URL = os.environ.get("TRUNK_PUBLIC_URL", "/")

SW_FILENAME = "sw.js"
IGNORE_EXTENSIONS = {".bin"}
IGNORE_FILES = {SW_FILENAME, "index.html"}  # index.html handled as root


def get_file_hash(filepath: Path) -> str:
    sha256 = hashlib.sha256()
    with filepath.open("rb") as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
    return sha256.hexdigest()


def scan_assets(directory: Path) -> Iterable[str]:
    base_url = PUBLIC_URL if PUBLIC_URL.endswith("/") else f"{PUBLIC_URL}/"

    yield base_url

    for root, _, files in os.walk(directory):
        for f in files:
            if f in IGNORE_FILES:
                continue

            file_path = Path(root) / f
            if file_path.suffix in IGNORE_EXTENSIONS:
                continue

            rel_path = file_path.relative_to(directory)
            yield f"{base_url}{rel_path.as_posix()}"


def generate_sw(assets: Sequence[str]) -> str:
    assets_json = json.dumps(assets)
    master_hash = hashlib.sha256(assets_json.encode("utf-8")).hexdigest()[:16]
    cache_name = f"am4-cache-{master_hash}"

    return (
        f"/* generated by scripts/generate_pwa_sw.py during trunk post_build */\n"
        f"const CACHE_NAME = '{cache_name}';\n"
        f"const ASSETS = {assets_json};\n"
        """
self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            console.log('[SW] pre-caching', ASSETS.length, 'files');
            return cache.addAll(ASSETS);
        })
    );
    self.skipWaiting();
});

self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys().then(keys => Promise.all(
            keys.map(key => key !== CACHE_NAME ? caches.delete(key) : Promise.resolve())
        ))
    );
    self.clients.claim();
});

self.addEventListener('fetch', event => {
    if (event.request.method !== 'GET') return;

    event.respondWith(
        caches.match(event.request).then(cached => {
            if (cached) return cached;

            return fetch(event.request).then(response => {
                // do not cache large binary files in sw cache (managed by idb in rust)
                if (!response || response.status !== 200 || response.type !== 'basic' || event.request.url.endsWith('.bin')) {
                    return response;
                }

                const responseToCache = response.clone();
                caches.open(CACHE_NAME).then(cache => {
                    cache.put(event.request, responseToCache);
                });

                return response;
            });
        })
    );
});
"""
    )


def main() -> None:
    assets = sorted(scan_assets(STAGING_DIR))
    sw_content = generate_sw(assets)
    sw_path = STAGING_DIR / SW_FILENAME

    sw_path.write_text(sw_content, encoding="utf-8")


if __name__ == "__main__":
    main()
